### ISSUE TITLE
Error: Cannot find module '/root/MagicMirror/serveronlyexport'

### ISSUE THREAD

**Issue by recklessnl** [Bee-Mar/mmpm#12]
I installed the package manager yesterday and now I'm getting this error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/MagicMirror/serveronlyexport'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

This definitely happened due to the package manager - any idea what could've caused it and how to fix it?

**Comment by recklessnl** [comment]
Let me do some more troubleshooting. It might be that something else went wrong. Still wrapping my head around this - might have been too fast to make this issue.
