### ISSUE TITLE
BUG: cannot install packages

### ISSUE THREAD

**Issue by ruralguru** [Bee-Mar/mmpm#142]
**sounds similar to #66. latin-1' codec can't encode character '\u25dc' **

Is this an issue with the CLI or GUI?
- CLI directly reports, GUI shows in log.

Is this something that should be put in the Wiki?

**To Reproduce**
1. mmpm install MMM-AirNow (or MMM-Pir, can also run from GUI on remote device)
2. See error (or review downloaded log from mmpm GUI)

**Expected behavior**
From previous install expected to install package and that package to become available in local packages.

**Screenshots**
(venv) pi@magicmirror:~ $ mmpm install MMM-AirNow
Matched query to 1 package
Install MMM-AirNow (https://github.com/nigel-daniels/MMM-AirNow)? [yes/y] or [no/n]: y
+ Installing MMM-AirNow
---- Cloning repository Traceback (most recent call last):
  File "/home/pi/venv/bin/mmpm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/mmpm/entrypoint.py", line 12, in main
    _main_(args)
  File "/home/pi/venv/lib/python3.11/site-packages/mmpm/mmpm.py", line 171, in main
    mmpm.core.install_packages(installation_candidates, assume_yes=args.assume_yes)
  File "/home/pi/venv/lib/python3.11/site-packages/mmpm/core.py", line 493, in install_packages
    error: str = install_package(package, assume_yes=assume_yes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/mmpm/core.py", line 532, in install_package
    error_code, _, stderr = mmpm.utils.clone(
                            ^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/mmpm/utils.py", line 309, in clone
    return run_cmd(command)
           ^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/mmpm/utils.py", line 234, in run_cmd
    sys.stdout.write(next(spinner))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25dc' in position 0: ordinal not in range(256)
(venv) pi@magicmirror:~ $ 

**Operating System, Python3 Version, and Web Browser**\
- output from `cat /etc/os-release`
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

- output from `python3 --version`
Python 3.11.2

- Web Browser (firefox, chrome, safari, chromium, etc)
chromium

**MMPM Environment Settings**

- output from `mmpm env`
mmpm env

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`
[mmpm-logs-2023-9-1(1).zip](https://github.com/Bee-Mar/mmpm/files/12913615/mmpm-logs-2023-9-1.1.zip)

**MagicMirror Config**
Note have replaces private content with ...s
- your MagicMirror `config.js`
/* MagicMirror² Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 *
 * You can use environment variables using a `config.js.template` file instead of `config.js`
 * which will be converted to `config.js` while starting. For more information
 * see https://docs.magicmirror.builders/configuration/introduction.html#enviromnent-variables
 */
let config = {
	address: "0.0.0.0",	// - "0.0.0.0", "::" to listen on any interface
	port: 8080,
	basePath: "/",			// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:172.17.0.1", "0.0.0.0", "..., "...."], //IP addresses allowed to view content
	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "imperial",

	modules: [
		{
            module: "mmpm" // allow mmpm to display status and show/hide modules.
        },
		{
			module: "newsfeed",
			position: "top_bar",
			config: {
				feeds: [
					{
						title: "Colorado Sun",
						url: "https://coloradosun.com/feed",
					}
				],
				showSourceTitle: true,
                updateInterval: 60000
			}
		},
        {
			module: "updatenotification",
			position: "top_center"
		},
		{
			module: "weather",
			position: "top_left",
			config: {
				weatherProvider: "openweathermap",
				type: "forcast",
				location: "Colorado Springs",
				locationID: "5417598",
				apiKey: "...",
                initialLoadDelay: "5000",
                updateInterval: "21600000",
                showHumidity: "true",
                showPrecipitationAmount: "true",
                showPrecipitationProbability: "true"
			}
		},
		{
			module: "weather",
			position: "top_left",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "Colorado Springs",
				locationID: "5417598",
				apiKey: "...,
                showHumidity: "true",
			}
		},
		{
			module: "clock",
			position: "top_right"
		},
	]
};

**Comment by ruralguru** [comment]
issue was that my local was using the ISO-8859-1 character set. changing to the TUF-8 character set resolved issue.
