### ISSUE TITLE
BUG: Initializing MagicMirror 3rd party packages database Traceback (most recent call last) produces an error

### ISSUE THREAD

**Issue by rcberg3** [Bee-Mar/mmpm#146]
**Describe the Bug**

Getting an error when searching or installing mopdules.

_Is this an issue with the CLI or GUI?_ CLI

_Is this something that should be put in the Wiki?_ maybe? seems to be a repeat, see 2 years ago: https://github.com/Bee-Mar/mmpm/issues/68

**To Reproduce**
1. A fresh install of raspbian, MagicMirror, and mmpm.
2. In terminal, search or install a module, for example: `mmpm search mbta` or `mmpm install MMM-MBTA`
3. Terminal gives the following response:
```
mmpm install MMM-MBTA
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/entrypoint.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/mmpm.py", line 51, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1054, in load_packages
    packages = retrieve_packages()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1135, in retrieve_packages
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1135, in <listcomp>
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 980, in __getattr__
    raise AttributeError(
AttributeError: 'NavigableString' object has no attribute 'contents'
```

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- output from `python3 --version`
Python 3.11.2

**MMPM Environment Settings**

- output from `mmpm env`
```
mmpm env
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/entrypoint.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/mmpm.py", line 51, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1054, in load_packages
    packages = retrieve_packages()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1135, in retrieve_packages
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1135, in <listcomp>
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 980, in __getattr__
    raise AttributeError(
AttributeError: 'NavigableString' object has no attribute 'contents'
```
**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

```
mmpm log --zip
 + Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/entrypoint.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/mmpm.py", line 51, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1054, in load_packages
    packages = retrieve_packages()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1135, in retrieve_packages
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.11/site-packages/mmpm/core.py", line 1135, in <listcomp>
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bs4/element.py", line 980, in __getattr__
    raise AttributeError(
AttributeError: 'NavigableString' object has no attribute 'contents'
```

**Comment by Bee-Mar** [comment]
@zerojarvis I'm currently in the midst of a total rework of the application and have put off fixing bugs to get it out ASAP. If you'd like to make a PR, please feel free

**Comment by slugmuffin** [comment]
thank you @zerojarvis - that helped

**Comment by Bee-Mar** [comment]
@zerojarvis @slugmuffin @rcberg3 has been released. This is a complete rework of the application with improvements and stability all-around. Please see [How to Migrate to 4.x.x](https://github.com/Bee-Mar/mmpm/wiki/Migrating-to-MMPM%E2%80%904.x.x) as well the rest of the pages in the [Wiki](https://github.com/Bee-Mar/mmpm/wiki)
