### ISSUE TITLE
BUG: Can't install UI or go through Guided-Setup

### ISSUE THREAD

**Issue by Z3r0shin** [Bee-Mar/mmpm#206]
The commands `mmpm ui install -y` and `mmpm guided-setup` return this

> usage: mmpm <subcommand> [option(s)]
> mmpm: error: argument subcmd: invalid choice: 'ui' (choose from 'search', 'install', 'remove', 'update', 'upgrade', 'db', 'list', 'open', 'show', 'add-ext-pkg', 'log', 'mm-ctl', 'env')

and

> usage: mmpm <subcommand> [option(s)]
> mmpm: error: argument subcmd: invalid choice: 'guided-setup' (choose from 'search', 'install', 'remove', 'update', 'upgrade', 'db', 'list', 'open', 'show', 'add-ext-pkg', 'log', 'mm-ctl', 'env')

respectively.

Is this an issue with the CLI or GUI?
CLI

Is this something that should be put in the Wiki?
I guess since I followed the installation wiki to the letter but can't proceed further.

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- output from `python3 --version`
Python 3.7.3

- Web Browser (firefox, chrome, safari, chromium, etc)
chrome, but through Portainer and TrueNAS Scale, both latest versions

**MMPM Environment Settings**

- output from `mmpm env`
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/usr/local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/mmpm/entrypoint.py", line 12, in main
    _main_(args)
  File "/usr/local/lib/python3.7/dist-packages/mmpm/mmpm.py", line 51, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/usr/local/lib/python3.7/dist-packages/mmpm/core.py", line 1054, in load_packages
    packages = retrieve_packages()
  File "/usr/local/lib/python3.7/dist-packages/mmpm/core.py", line 1135, in retrieve_packages
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
  File "/usr/local/lib/python3.7/dist-packages/mmpm/core.py", line 1135, in <listcomp>
    categories: list = [category.contents[-1].contents[0] for category in categories_soup][2:]
  File "/usr/local/lib/python3.7/dist-packages/bs4/element.py", line 986, in __getattr__
    self.__class__.__name__, attr))
AttributeError: 'NavigableString' object has no attribute 'contents'

**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm logs --zip`
usage: mmpm <subcommand> [option(s)]
mmpm: error: argument subcmd: invalid choice: 'logs' (choose from 'search', 'install', 'remove', 'update', 'upgrade', 'db', 'list', 'open', 'show', 'add-ext-pkg', 'log', 'mm-ctl', 'env')

**MagicMirror Config**

- your MagicMirror `config.js`
Its the same as the default one, I haven't messed with it yet.

**Comment by Bee-Mar** [comment]
You're using Python 3.7.3, and the latest version of MMPM doesn't support anything below Python 3.8 (soon to be Python 3.9 as the minimum). I'm not sure which version of MMPM you have installed, but Pip probably resolved your installation to an older version of MMPM

**Comment by Bee-Mar** [comment]
@Z3r0shin , have you updated your version of python and tried with the newest version of MMPM?

**Comment by Z3r0shin** [comment]
I tried all I could before letting go. I haven't tested the newest version yet, I decided to go with a simple kiosk option.
