### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by usafmaverick** [Bee-Mar/mmpm#32]
Fresh install of Ubuntu 16.04 LTS, fresh install of MagicMirror to ~/MagicMirror, minimal layout configuration and no extra modules.

Trying to install mmpm using the all in one command provided on the install wiki. It installs successfully, however when I navigate to myipaddress:7890 I get a 502 Bad Gateway error. Initially I ran the all in one command from ~, so I did make uninstall and tried reinstalling mmpm in the MagicMirror root directory with no change.

What am i missing here?

**Comment by Bee-Mar** [comment]
can you attach any output from the logs that looks relevant? The logs will be in `~/.config/mmpm/log`. Also, please attach output from `sudo systemctl mmpm`, and `sudo systemctl status mmpm-webssh`

It sounds like the WSGI server failed to start. I'll check this out on a VM soon

**Comment by usafmaverick** [comment]
Python 2.7.12, Python3 3.5.2

login as: root
root@10.0.0.16's password:
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.15.18-10-pve x86_64)
Copied below is the status of mmpm-webssh and Ive attached the log files as requested.
[mmpm-gunicorn-error.log](https://github.com/Bee-Mar/mmpm/files/4879453/mmpm-gunicorn-error.log)


: 
`root@magicmirror:~# sudo systemctl status mmpm-webssh
* mmpm-webssh.service - MMPM WebSSH daemon
   Loaded: loaded (/etc/systemd/system/mmpm-webssh.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-07-06 14:00:02 UTC; 10min ago
 Main PID: 242 (wssh)
   CGroup: /system.slice/mmpm-webssh.service
           `-242 /usr/bin/python3 /root/.local/bin/wssh --address=127.0.0.1 --port=7893

Jul 06 14:00:02 magicmirror systemd[1]: Started MMPM WebSSH daemon.
Jul 06 14:00:03 magicmirror wssh[242]: [I 200706 14:00:03 settings:125] WarningPolicy
Jul 06 14:00:03 magicmirror wssh[242]: [I 200706 14:00:03 main:39] Listening on 127.0.0.1:7893 (http)
root@magicmirror:~#
`

**Comment by Bee-Mar** [comment]
Well, you’ll definitely need to upgrade to python 3.6 or higher. This package is incompatible with anything lower than 3.6. Try upgrading, and reinstalling MMPM

**Comment by usafmaverick** [comment]
Updated to Python3 version 3.6.3, ran make uninstall, rebooted, the reran the all in one command. Now Im getting a different error. Included below:

root@magicmirror:~# git clone https://github.com/Bee-Mar/mmpm.git && \
>       cd mmpm && \
>       make && \
>       echo "export PATH=$PATH:$HOME/.local/bin" >> $HOME/.bashrc && \
>       source ~/.bashrc
Cloning into 'mmpm'...
remote: Enumerating objects: 476, done.
remote: Counting objects: 100% (476/476), done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 5211 (delta 226), reused 341 (delta 116), pack-reused 4735
Receiving objects: 100% (5211/5211), 6.30 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3009/3009), done.
Checking connectivity... done.
--------------------------------------------
| Removing legacy installation destination |
--------------------------------------------
------------------------------
| Gathering CLI dependencies |
------------------------------
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (8.1.1-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
1 location(s) to search for versions of setuptools:
* https://pypi.python.org/simple/setuptools/
Getting page https://pypi.python.org/simple/setuptools/
Looking up "https://pypi.python.org/simple/setuptools/" in the cache
Returning cached "301 Moved Permanently" response (ignoring date and etag information)
Looking up "https://pypi.org/simple/setuptools/" in the cache
Current age based on date: 3848
Freshness lifetime from max-age: 600
Freshness lifetime from request max-age: 600
Starting new HTTPS connection (1): pypi.org
Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
Installed version (28.8.0) is most up-to-date (past versions: none)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/site-packages
Collecting wheel
  1 location(s) to search for versions of wheel:
  * https://pypi.python.org/simple/wheel/
  Getting page https://pypi.python.org/simple/wheel/
  Looking up "https://pypi.python.org/simple/wheel/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/wheel/" in the cache
  Current age based on date: 3848
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (2): pypi.org
  Could not fetch URL https://pypi.python.org/simple/wheel/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement wheel (from versions: )
Cleaning up...
No matching distribution found for wheel
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.6/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for wheel
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
Returning cached "301 Moved Permanently" response (ignoring date and etag information)
Looking up "https://pypi.org/pypi/pip/json" in the cache
Current age based on date: 36529
Freshness lifetime from max-age: 900
Starting new HTTPS connection (1): pypi.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 808, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
pip._vendor.requests.packages.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting setuptools>=45.0.0 (from -r requirements.txt (line 1))
  1 location(s) to search for versions of setuptools:
  * https://pypi.python.org/simple/setuptools/
  Getting page https://pypi.python.org/simple/setuptools/
  Looking up "https://pypi.python.org/simple/setuptools/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/setuptools/" in the cache
  Current age based on date: 3848
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (1): pypi.org
  Could not fetch URL https://pypi.python.org/simple/setuptools/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement setuptools>=45.0.0 (from -r requirements.txt (line 1)) (from versions: )
Cleaning up...
No matching distribution found for setuptools>=45.0.0 (from -r requirements.txt (line 1))
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.6/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for setuptools>=45.0.0 (from -r requirements.txt (line 1))
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
Returning cached "301 Moved Permanently" response (ignoring date and etag information)
Looking up "https://pypi.org/pypi/pip/json" in the cache
Current age based on date: 36529
Freshness lifetime from max-age: 900
Starting new HTTPS connection (1): pypi.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 808, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
pip._vendor.requests.packages.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
Makefile:28: recipe for target 'dependencies-cli' failed
make: *** [dependencies-cli] Error 1

**Comment by usafmaverick** [comment]
Update: Updating to python 3.7.2 did the trick. Web interface seems to be working as expected. Thanks for the help.

**Comment by Bee-Mar** [comment]
@usafmaverick no problem, and glad it's working for you! I'll go ahead an update the wiki to specify 3.7 or greater. Also, there will be a pretty major upgrade in all aspects of the application in a couple weeks.
