### ISSUE TITLE
This Normal?

### ISSUE THREAD

**Issue by swvalenti194** [Bee-Mar/mmpm#55]
`pi@raspberrypi:~ $ mmpm update
Checking MMM-FlightRadarTracker [package] for updates ✓
Checking MMM-DarkSkyForecast [package] for updates ✓
Checking MMM-RTSPStream [package] for updates ✓
Checking MMM-EventHorizon [package] for updates ✓
Checking MMM-News [package] for updates ✓
Checking MMM-PGA [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 139, in main
    mmpm_upgrade: bool = mmpm.core.check_for_mmpm_updates()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 103, in check_for_mmpm_updates
    json.dump(upgrades, available_upgrades)
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMirrorPackage is not JSON serializable
pi@raspberrypi:~ $ `

**Comment by swvalenti194** [comment]
`pi@raspberrypi:~ $ mmpm update
Checking MMM-FlightRadarTracker [package] for updates ✓
Checking MMM-DarkSkyForecast [package] for updates ✓
Checking MMM-RTSPStream [package] for updates ✓
Checking MMM-EventHorizon [package] for updates ✓
Checking MMM-News [package] for updates ✓
Checking MMM-PGA [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 139, in main
    mmpm_upgrade: bool = mmpm.core.check_for_mmpm_updates()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 103, in check_for_mmpm_updates
    json.dump(upgrades, available_upgrades)
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMirrorPackage is not JSON serializable
pi@raspberrypi:~ $ `

**Comment by swvalenti194** [comment]
Run mmpm update and this is the return...

**Comment by Bee-Mar** [comment]
@swvalenti194 anytime this type of error occurs, it's usually due to someone entering bad info/unexpected html tags into the MagicMirror 3rd party wiki list. Have you tried re-running `mmpm update` lately?

**Comment by swvalenti194** [comment]
Just ran it same error returns

**Comment by MikeBishop** [comment]
Seeing the same thing.

**Comment by Bee-Mar** [comment]
@swvalenti194 @MikeBishop have you attempted to reinstall mmpm? I'm unable to reproduce this. 

Can you try running:
```sh
python3 -m pip install --upgrade --force-reinstall --no-cache-dir mmpm
```
and rerun your previous command?

**Comment by swvalenti194** [comment]
@Bee-Mar Still getting the same error after running your command.

**Comment by Bee-Mar** [comment]
try deleting your database, and then running `mmpm db --refresh`

```sh
rm ~/.config/mmpm/MagicMirror*
mmpm db --refresh
```

**Comment by swvalenti194** [comment]
Still getting same issue

`pi@raspberrypi:~ $ rm ~/.config/mmpm/MagicMirror*
pi@raspberrypi:~ $ mmpm db --refresh
+ Initializing MagicMirror 3rd party packages database ✓
Checking MMPM [application] (automated) for updates ✓
pi@raspberrypi:~ $ mmpm update
Checking MMM-FlightRadarTracker [package] for updates ✓
Checking MMM-DarkSkyForecast [package] for updates ✓
Checking MMM-PGA [package] for updates ✓
Checking MMM-RTSPStream [package] for updates ✓
Checking MMM-EventHorizon [package] for updates ✓
Checking MMM-News [package] for updates ✓
Checking MMM-PGA [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 139, in main
    mmpm_upgrade: bool = mmpm.core.check_for_mmpm_updates()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 103, in check_for_mmpm_updates
    json.dump(upgrades, available_upgrades)
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMirrorPackage is not JSON serializable
`

**Comment by swvalenti194** [comment]
> pi@raspberrypi:~ $ rm ~/.config/mmpm/MagicMirror*
pi@raspberrypi:~ $ mmpm db --refresh
+ Initializing MagicMirror 3rd party packages database ✓
Checking MMPM [application] (automated) for updates ✓
pi@raspberrypi:~ $ mmpm update
Checking MMM-FlightRadarTracker [package] for updates ✓
Checking MMM-DarkSkyForecast [package] for updates ✓
Checking MMM-PGA [package] for updates ✓
Checking MMM-RTSPStream [package] for updates ✓
Checking MMM-EventHorizon [package] for updates ✓
Checking MMM-News [package] for updates ✓
Checking MMM-PGA [package] for updates ✓
Checking MagicMirror [application] for updates ✓
Checking MMPM [application] for updates ✓
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 139, in main
    mmpm_upgrade: bool = mmpm.core.check_for_mmpm_updates()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 103, in check_for_mmpm_updates
    json.dump(upgrades, available_upgrades)
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMirrorPackage is not JSON serializable>

**Comment by Bee-Mar** [comment]
@swvalenti194 i think i've found the issue

**Comment by Bee-Mar** [comment]
@swvalenti194 i may have spoken too soon. Can you also try removing the cached list of available upgrades then re-run `mmpm update`

```sh
rm ~/.config/mmpm/mmpm-available-upgrades.json
mmpm update
```

**Comment by Bee-Mar** [comment]
something else worth trying is uninstalling all the packages, and then reinstalling them. If `mmpm list -it` will produce output, then you can try the following:

```sh
mmpm list -it > packages.txt; mmpm remove -y $(cat packages.txt); mmpm install -y $(cat packages.txt)
```

**Comment by swvalenti194** [comment]
Still did not work sir

**Comment by swvalenti194** [comment]
running your last command now standby

**Comment by swvalenti194** [comment]
> something else worth trying is uninstalling all the packages, and then reinstalling them. If `mmpm list -it` will produce output, then you can try the following:
> 
> ```shell
> mmpm list -it > packages.txt; mmpm remove -y $(cat packages.txt); mmpm install -y $(cat packages.txt)
> ```

This worked!  You da man thank you!  What the reasoning behind this?

**Comment by Bee-Mar** [comment]
@MikeBishop the command below worked for @swvalenti194 , hopefully it fixes the issue for you as well.

```sh
mmpm list -it > packages.txt; mmpm remove -y $(cat packages.txt); mmpm install -y $(cat packages.txt)
```

**Comment by Bee-Mar** [comment]
@swvalenti194 well, unfortunately that's something I'll have to look into lol. On the surface it makes no sense to me since the python object is most certainly getting serialized into a JSON friendly format prior to writing the contents to a file.

**Comment by swvalenti194** [comment]
Well shit, the update worked but now my mirror is just black screen.  Pm2 shows processes started but no modules display

**Comment by Bee-Mar** [comment]
did you shut down the mirror prior to reinstalling your packages?

**Comment by swvalenti194** [comment]
No but I will try that now and report back

**Comment by swvalenti194** [comment]
ugggghhhhhhh it's just a black screen still

**Comment by Bee-Mar** [comment]
@swvalenti194 this would have to be related to one of the modules at this point. I'd suggest commenting out modules one by one in your config.js and restarting magicmirror each time

**Comment by swvalenti194** [comment]
It was fine before running that last command you sent, don't think its a config issue as I am not getting a config error on the black screen

**Comment by Bee-Mar** [comment]
@swvalenti194 the only thing that previous command did was reinstall the packages you already had installed

**Comment by swvalenti194** [comment]
Ok I have found the module MMM-PGA that is causing the issue, not sure why as it was working before.

**Comment by Bee-Mar** [comment]
I can only assume there were changes made to the module that weren't pulled down before since you weren't able to update through mmpm
