### ISSUE TITLE
BUG: Cannot run guided-setup

### ISSUE THREAD

**Issue by serenewaffles** [Bee-Mar/mmpm#66]
**Describe the Bug**

Is this an issue with the CLI or GUI?
CLI issue

Is this something that should be put in the Wiki?
Unlikely

When I try to run `mmpm --guided-setup` I get a UnicodeEncodeError, and setup fails.

**To Reproduce**
run the following commands
```
sudo apt install libffi-dev nginx-full -y
python3 -m pip install --upgrade --no-cache-dir mmpm
echo 'export PATH="$PATH:$HOME/.local/bin"' >> ~/.bashrc
mmpm --guided-setup
```

**Expected behavior**
mmpm should perform a setup

**Screenshots**
```
pi@magicmirror:~ $ mmpm --guided-setup
Welcome to MMPM's guided setup!

I'll help you setup your environment variables, and install additional features. Pressing CTRL-C will cancel the entire process.
There are 6 to 12 questions, depending on your answers. Let's get started.

What is the absolute path to the root of your MagicMirror installation (ie. /home/pi/MagicMirror)? /home/pi/MagicMirror
Did you install MMPM as a Docker image, or using docker-compose? [yes/y] or [no/n]: n
Did you install MagicMirror using docker-compose? [yes/y] or [no/n]: n
Are you currently using PM2 with your MagicMirror? [yes/y] or [no/n]: n
Is http://192.168.0.210:8080 the address used to open MagicMirror in your browser?  [yes/y] or [no/n]: y
Have you ever installed any version of MMPM < 2.01? [yes/y] or [no/n]: n
Would you like to install the MMPM GUI (web interface)? [yes/y] or [no/n]: y
Would you like to hide/show MagicMirror modules through MMPM? [yes/y] or [no/n]: n
Would you like to install tab-autocomplete for the MMPM CLI? [yes/y] or [no/n]: y
Are you sure you want to install the MMPM GUI? This requires sudo permission. [yes/y] or [no/n]: yes
Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 38, in main
    mmpm.core.guided_setup()
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 2469, in guided_setup
    install_mmpm_gui(assume_yes=True)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 714, in install_mmpm_gui
    remove_mmpm_gui(hide_prompt=True)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 885, in remove_mmpm_gui
    print(f'{mmpm.consts.GREEN_PLUS} MMPM SystemD service not active, nothing to do {mmpm.consts.GREEN_CHECK_MARK}')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 73: ordinal not in range(256)
```

**Operating System, Python3 Version, and Web Browser**\
(Please complete the following information)

- output from `cat /etc/os-release`
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
- output from `python3 --version`
`Python 3.7.3`

- Web Browser (firefox, chrome, safari, chromium, etc)
N/A

**MMPM Environment Settings**

- output from `mmpm env`
```
pi@magicmirror:~ $ mmpm env
+ Initializing MagicMirror 3rd party packages database Traceback (most recent call last):
  File "/home/pi/.local/bin/mmpm", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 12, in main
    _main_(args)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 48, in main
    packages: Dict[str, List[MagicMirrorPackage]] = mmpm.core.load_packages(force_refresh=should_refresh)
  File "/home/pi/.local/lib/python3.7/site-packages/mmpm/core.py", line 1123, in load_packages
    print(mmpm.consts.GREEN_CHECK_MARK)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 10: ordinal not in range(256)
```
**MMPM Log Files**

- Attach the file produced `Download MMPM log files` within the Control Center of the GUI or from the  `mmpm log --zip`

**MagicMirror Config**

- your MagicMirror `config.js`

**Comment by lthown** [comment]
Getting the same error, tried using a remote terminal and local terminal.

**Comment by lthown** [comment]
Edit /home/pi/.local/lib/python3.7/site-packages/mmpm/consts.py

change lines 32-34 to no longer use unicode emojis:

`GREEN_CHECK_MARK: str = mmpm.color.N_GREEN + '+' + mmpm.color.RESET
YELLOW_X: str = mmpm.color.N_YELLOW + 'x' + mmpm.color.RESET
RED_X: str = mmpm.color.N_RED + 'X' + mmpm.color.RESET`

**Comment by Bee-Mar** [comment]
@lthown this solved the issue for you?

**Comment by lthown** [comment]
> @lthown this solved the issue for you?

Yep, after editing that it worked perfectly.

**Comment by Bee-Mar** [comment]
If you'd like you can make a merge request. Otherwise I'll make the change shortly

**Comment by Bee-Mar** [comment]
@ernade have you tried reinstalling? that file should get pulled down from PIP when installing
