### ISSUE TITLE
BUG: "mmpm --guided-setup" error 

### ISSUE THREAD

**Issue by Kieran1375** [Bee-Mar/mmpm#79]
Traceback (most recent call last):                                                                                                                                                                                    File "/home/pi/.local/bin/mmpm", line 6, in <module>                                                                                                                                                                  from mmpm.__main__ import main                                                                                                                                                                                    File "/home/pi/.local/lib/python3.7/site-packages/mmpm/__main__.py", line 4, in <module>                                                                                                                              from mmpm.mmpm import main as _main_                                                                                                                                                                              File "/home/pi/.local/lib/python3.7/site-packages/mmpm/mmpm.py", line 6, in <module>                                                                                                                                  import mmpm.utils                                                                                                                                                                                                 File "/home/pi/.local/lib/python3.7/site-packages/mmpm/utils.py", line 15, in <module>                                                                                                                                import mmpm.consts                                                                                                                                                                                                File "/home/pi/.local/lib/python3.7/site-packages/mmpm/consts.py", line 58, in <module>                                                                                                                               MMPM_MAGICMIRROR_URI_ENV: f'http://{gethostbyname(gethostname())}:8080',                                                                                                                                        socket.gaierror: [Errno -2] Name or service not known

I've installed the module as per instructions but when running the setup I get this error. 
Any ideas?

**Comment by Bee-Mar** [comment]
at what point in the guided setup does this error occur?

**Comment by Kieran1375** [comment]
Just solved it. It was due to an underscore in the hostname.
Checked what the error means and it's something to do with the hostname so I changed the name from "Magic_Mirror" to just "MagicMirror" in both /etc/hosts + /etc/hostname
