### ISSUE TITLE
installation broken

### ISSUE THREAD

**Issue by khassel** [Bee-Mar/mmpm#93]
When starting mmpm in the docker container with `/home/node/.local/bin/gunicorn --reload --worker-class eventlet --bind localhost:7891 mmpm.wsgi:app --user=node` I'm now getting these errors:

```bash
[2022-03-05 22:38:29 +0000] [43] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
    super().init_process()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/node/.local/lib/python3.8/site-packages/mmpm/wsgi.py", line 6, in <module>
    from mmpm.api import app
  File "/home/node/.local/lib/python3.8/site-packages/mmpm/api.py", line 8, in <module>
    from flask_cors import CORS
  File "/home/node/.local/lib/python3.8/site-packages/flask_cors/__init__.py", line 11, in <module>
    from .decorator import cross_origin
  File "/home/node/.local/lib/python3.8/site-packages/flask_cors/decorator.py", line 13, in <module>
    from flask import make_response, request, current_app
  File "/home/node/.local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/node/.local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/node/.local/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

This worked with my last dependency build in Dec. 2021. So I digged deeper and compared the changed python deps:

Working one from Dec.:
```
MarkupSafe-2.0.1 
Werkzeug-2.0.2 
argcomplete-1.12.3 
click-8.0.3 
colorama-0.4.4 
cryptography-36.0.1 
eventlet-0.30.1 
flask-socketio-5.1.1 
mmpm-2.12 
paramiko-2.8.1 
pygments-2.10.0 
pynacl-1.4.0 
python-engineio-4.3.0 
python-socketio-5.5.0 
websocket-client-1.2.3
```

Now not working:
```bash
MarkupSafe-2.1.0 
Werkzeug-2.0.3 
argcomplete-2.0.0 
click-8.0.4 
colorama-0.4.4 
cryptography-36.0.1 
eventlet-0.30.1 
flask-socketio-5.1.1 
mmpm-2.12 
paramiko-2.9.2 
pygments-2.11.2 
pynacl-1.5.0 
python-engineio-4.3.1 
python-socketio-5.5.2 
websocket-client-1.3.1
```

Because I have no python knowledge and no real debug setup I need help how to solve this (e.g. which package has to be fixed to a specific version), thanks.

**Comment by khassel** [comment]
I nailed "itsdangerous==2.0.1" in the requirements to get this working again, but this should be fixed here.

AFAIS this is no docker problem so I changed the title.

**Comment by Bee-Mar** [comment]
There have been a number of automated pull requests created to update versions. I'm working on the develop branch locally to get it all resolved. Gotta love dependency issues lol

**Comment by khassel** [comment]
> Also, I can't seem to reproduce the error you're encountering

issue is more than 4 weeks old so may dependencies changed again ...

**Comment by Bee-Mar** [comment]
@khassel I've pushed changes for version 2.13, and it's up on PyPi now. Hopefully the install in docker works smoothly. I'm also going to be upgrading the GUI to use a more recent version of Angular, but that _shouldn't_ cause any build issues

**Comment by khassel** [comment]
With `2.13` the `itsdangerous` problem seems to be solved but now I'm getting:

```bash
[2022-04-30 20:32:23 +0000] [44] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/workers/geventlet.py", line 134, in init_process
    super().init_process()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/node/.local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/node/.local/lib/python3.8/site-packages/mmpm/wsgi.py", line 6, in <module>
    from mmpm.api import app
  File "/home/node/.local/lib/python3.8/site-packages/mmpm/api.py", line 8, in <module>
    from flask_cors import CORS
  File "/home/node/.local/lib/python3.8/site-packages/flask_cors/__init__.py", line 11, in <module>
    from .decorator import cross_origin
  File "/home/node/.local/lib/python3.8/site-packages/flask_cors/decorator.py", line 13, in <module>
    from flask import make_response, request, current_app
  File "/home/node/.local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/home/node/.local/lib/python3.8/site-packages/jinja2/__init__.py)
```

To be honest I have no time to dig in these python stuff so there will be no new docker image for `2.13` until this is solved.

This happens with python 3.8 on bullseye.

**Comment by Bee-Mar** [comment]
I'll look into this now and let you know when it looks good to retry.

**Comment by Bee-Mar** [comment]
@khassel just created a 2.14 version which should address the issue you encountered. Nothing like dependency hell lol

**Comment by khassel** [comment]
Thanks, could test it on arm64, works there. Will provide the new images tomorrow (arm image build needs ~ 2h and I'm 6 hours ahead ...)

**Comment by Bee-Mar** [comment]
Whenever you get a chance is more than fine. The docker image wouldn't exist without you anyway!

**Comment by Bee-Mar** [comment]
@khassel let me know when things work for you so I can close this issue

**Comment by khassel** [comment]
Its working so I will close this now. The images for version 2.14 are available on docker hub.

At the moment I'm struggling with on of your favorite errors, the not working active module page ...

**Comment by Bee-Mar** [comment]
Did you ever get that to work? I didn't expect that to ever work with the docker images

**Comment by khassel** [comment]
yes, works. Found my problem, was self made ...
